### ISSUE TITLE
Can you add Move Runner as a compile tool in your README

### ISSUE THREAD

**Issue by liangping** [pontem-network/vscode-move-ide#5]
Here's Homepage of Move Runner. 
https://github.com/ping-pub/move-runner

We will also add your project in our [tutorials](https://github.com/ping-pub/move-runner/blob/master/docs/02_integrate_with_ide.md) later

**Comment by damirka** [comment]
Hi, @liangping! There's a problem: your tool only supports **Move IR** (.mvir) whereas my package mainly supports **Move** (Move compiler, Move language server and Move syntax).

You still can reference my package as it's the best and only syntax highlighting you can get for both Move and Mvir, but I can't integrate it with yours until:

1. you add support for Move (tools `move-build`, `move-check`);
2. make your directory structure compatible with structure In [this README](https://github.com/damirka/vscode-move-ide#recomended-directory-structure);

Will be waiting for your future actions!
Ping me when you're ready with Move language! And then we'll talk! 👍 

To learn why I chose Move, see [this link](https://move-book.com/introduction/move.or.mvir.html).

**Comment by liangping** [comment]
Thanks @damirka for replying.  
> you add support for Move (tools move-build, move-check);

will support Move in future. Let's keep in touch.

> To learn why I chose Move, see this link.

Let developers chose what they like, I prefer to .mvir.

What do you think of `vscode-libra-move` which is provided by @sdkbox.  
https://github.com/sdkbox/vscode-libra-move

**Comment by damirka** [comment]
About that package. If you look closely at their codebase it's outdated. Move is rapidly developing and changing - you can't use 10-month old packages in this case.

Plus, their source files are no more than C++ copy-pasted syntax with modifications. I've built syntax highlighting especially for Move and Mvir from scratch.

For example:
- keyword `acquires` in my package will only be highlighted in function definition;
- Move IDE won't highlight incorrect keywords inside struct definition;
- resource generic params differ from function generics, this package handles it well;
...more cases you can see [here](https://github.com/damirka/vscode-move-ide/blob/master/syntaxes/move.tmLanguage.json#L172)

And...
 > Let developers chose what they like, I prefer to .mvir.

Look again [at libra code](https://github.com/libra/libra/tree/master/language/stdlib/modules). There's no more `stdlib` written in Mvir - it's all Move now. And you can't sell or ship Mvir-like language - it's way to hard to understand. That why you'd better pick Move.

**Comment by liangping** [comment]
Sounds great, I will install your plugin, and add it to my tutorials.

> Look again at libra code. There's no more stdlib written in Mvir - it's all Move now. And you can't sell or ship Mvir-like language - it's way to hard to understand. That why you'd better pick Move.

I thought move is only used for stdlib, I will take a close look, thanks.

**Comment by damirka** [comment]
Sure! Feel free to suggest integrations! I hope this was helpful!
